# Generated by Django 3.1.4 on 2020-12-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data_uploaded',
            new_name='date_uploaded',
        ),
    ]
